💄  Add: mypage-review_UI
Team-Just-Do-it/Down-to-Earth pull request #7
Opened 2022-03-20 10:40 UTC by wjdgml3834

- 리뷰 작성하는 페이지를 만들고 스타일을 적용하였습니다
- 나중에 머지가 모두 완료되면, mypage가 있는 폴더로 옮기 예정입니다.

2022-03-20 13:48 UTC, Luceta approved these changes
컴포넌트 변수명들을 Cont  카운트인지  content 줄임말인지 더욱 명시적으로 구체적으로 수정 해주시면 더 좋을 거 같습니다.

수고하셨습니다.

2022-03-20 13:48 UTC, Luceta commented on src/pages/review.tsx
> +              <StarCont>
p3 :  축약보다는 명시적으로 적어주는 것이 좋을 것 같습니다. 
```suggestion
              <StarConunt> or <StarRating>
```

2022-03-20 13:48 UTC, Luceta commented on src/pages/review.tsx
> +              <ReviewInp
위와 상동
```suggestion
              <ReviewInput>
```

2022-03-20 13:48 UTC, Luceta commented on src/pages/review.tsx
> +              <ReviewSubmitBtn type="submit">등록하기</ReviewSubmitBtn>
p4: 이름이 겹치지만 않는다면 이렇게 해줘도 좋을 것 같아요
```suggestion
              <ReviewSubmit type="submit">등록하기</ReviewSubmit>
```

2022-03-20 14:06 UTC, Luceta requested changes
Styled component이름만 보고 무엇을 뜻하는지 알도록 네이밍에 구체적으로 적어주시면 더 좋을 것 같아보입니다.

2022-03-20 14:12 UTC, jiseung-kang approved these changes, later dismissed
고생 많으셨습니다~!

2022-03-21 01:09 UTC, wjdgml3834 commented on src/pages/review.tsx
> +              <StarCont>
<StarCount>말씀하시는거 맞죠? 저것은 StarContainer라고 적은건데 저번 피드백
반영해서 구체적으로 적겠습니다

2022-03-21 14:36 UTC, junep16 submitted a review, later dismissed
고생하셨습니다!

2022-03-22 12:51 UTC, Luceta commented on src/pages/review.tsx
> +              <StarCont>
넵! 반영해주시면 재리뷰 하겟습니다

2022-03-23 13:39 UTC, Luceta approved these changes

2022-03-23 13:40 UTC, Luceta approved these changes
수고하셨습니다!
좀더 네이밍에 신경써보와요!

2022-03-23 13:42 UTC, junep16 approved these changes
고생하셨습니다!

2022-03-23 14:20 UTC, merged