💄🚑  Feature/product review
Team-Just-Do-it/Down-to-Earth pull request #9
Opened 2022-03-21 14:00 UTC by Luceta

- 제품 상세페이지 UI완료
- button 컴포넌트로 props 내려서 공통적으로 사용하도록 모듈화 함( 현재 개발자 도구 emotion 이슈있음 해결 요망바랍니다. 다 적용했는데 안되네요...ㅜ)

2022-03-21 14:06 UTC, chilldata requested changes
지난번에 제 PR에서도 별점 관련 아이콘을 추가했어서 중복으로 추가될 가능성이 있어보입니다.
파일이름은 달라서 충돌은 안날것 같은데, 같이 얘기해보고 중복되는것은 제거하는 편이 좋아보입니다.

고생많으셨습니다

2022-03-21 18:54 UTC, Luceta commented
> 지난번에 제 PR에서도 별점 관련 아이콘을 추가했어서 중복으로 추가될 가능성이 있어보입니다. 파일이름은 달라서 충돌은 안날것 같은데, 같이 얘기해보고 중복되는것은 제거하는 편이 좋아보입니다.
> 
> 고생많으셨습니다

넵 그러시죠! 근데 code 개선사항이 아닌 경우는 이렇게 request changed가 아니라 comment만 남기셔도 됩니다.

2022-03-21 18:55 UTC, Luceta commented
> > 지난번에 제 PR에서도 별점 관련 아이콘을 추가했어서 중복으로 추가될 가능성이 있어보입니다. 파일이름은 달라서 충돌은 안날것 같은데, 같이 얘기해보고 중복되는것은 제거하는 편이 좋아보입니다.
> > 고생많으셨습니다
> 
> 넵 그러시죠! 근데 code 개선사항이 아닌 경우는 이렇게 request changed가 아니라 comment만 남기셔도 됩니다.
심각한 이슈나 뭔가 합치기 전에 손을 봐야될 경우 그럴때 이슈인 경우 request changed를 합니다. 찾아보시면 좋을 것 같습니다.

2022-03-22 05:00 UTC, jiseung-kang commented on src/components/ProductDetail/index.tsx
> +>>>>>>> e553cc2 (💄Add: Review Component and add on pageDetail):src/components/ProductDetail/index.tsx
p1: 이 부분 확인 부탁드려요!

2022-03-22 06:36 UTC, jiseung-kang approved these changes

2022-03-22 07:24 UTC, wjdgml3834 approved these changes
고생하셨습니다 :)

2022-03-22 10:04 UTC, merged